program BlackBlazentWelcome
    implicit none

    print *, "# 🔹 Welcome to BlackBlazent"
    print *, ""
    print *, "**BlackBlazent** is an independent software organization creating hybrid, cross-platform apps —"
    print *, "designed with passion, purpose, and precision."
    print *, "--------------------------------------------------------------------------------"
    print *, "## 🚀 About Us"
    print *, ""
    print *, "We are a startup software company focused on building modern, user-centered digital tools."
    print *, "From music and video apps to creative galleries, we aim to make hybrid apps accessible and meaningful."
    print *, "--------------------------------------------------------------------------------"
    print *, "## 🎯 Our Application Goals"
    print *, ""
    print *, "Every application created under **BlackBlazent** is built with a clear purpose."
    print *, "We focus on solving real-world problems through hybrid technology, beautiful design, and intuitive user experience."
    print *, ""
    print *, "### 🌟 Core Goals Behind Our Apps"
    print *, "1. ✅ Cross-Platform Experience - Deliver seamless functionality on desktop, web, and mobile."
    print *, "2. 🎨 Creative & Visual Engagement - Visually rich interfaces that are enjoyable to use."
    print *, "3. ⚙️ Practical Functionality - Tools supporting productivity, entertainment, creativity."
    print *, "4. 📱 Hybrid Technology Stack - Modern frameworks for faster, wider development."
    print *, "5. 🔐 User-First Design - Privacy, simplicity, and accessibility prioritized."
    print *, "6. 🌍 Global Accessibility - Localizable for users around the world."
    print *, "--------------------------------------------------------------------------------"
    print *, "🧭 Our mission is to build purposeful digital tools that blend art, function, and future-ready tech."
    print *, "--------------------------------------------------------------------------------"
    print *, "## 📦 Featured Projects"
    print *, ""
    print *, "| Icon | Project Name | Description | Version | Tech Stack |"
    print *, "|------|--------------|-------------|---------|------------|"
    print *, "| [bmusic.png] | BlackMusic | Music Ultra Superior Integrated Catalog. | v1.1.01.001.0001 | Undisclosed |"
    print *, "| [🖼️] | BlackVideo | Versatile Integrated Demi Empowerment Optimum—Player. | v1.0.0 | Undisclosed |"
    print *, "| [📸] | BlackGallery | Showcase and organize your visual content. | v1.0.0 | Undisclosed |"
    print *, "| [🧰] | BlackMiscellen | An Integrated Miscellaneous tools. | v1.0.0 | Undisclosed |"
    print *, "--------------------------------------------------------------------------------"
    print *, "## 👤 Join or Follow Us"
    print *, ""
    print *, "We’re always open to contributors, testers, and idea sharers!"
    print *, ""
    print *, "### 🔧 General & Administrative"
    print *, "| Purpose               | Email                                    |"
    print *, "|-----------------------|------------------------------------------|"
    print *, "| Main                  | blackblazent@gmail.com                   |"
    print *, "| Customer Support      | blackblazent.customer.service@gmail.com |"
    print *, "| Billing & Payments    | blackblazent.billing@gmail.com          |"
    print *, "| Legal or Compliance   | blackblazent.legal@gmail.com            |"
    print *, "| General Inquiries     | blackblazent.info@gmail.com             |"
    print *, ""
    print *, "### 🧑‍💻 Development & Technical"
    print *, "| Developer Support     | blackblazent.dev@gmail.com              |"
    print *, "| Bug Reports           | blackblazent.techsupport@gmail.com      |"
    print *, ""
    print *, "### 📣 Marketing & Outreach"
    print *, "| Marketing Team        | blackblazent.marketing@gmail.com        |"
    print *, "| Partnerships          | blackblazent.partners@gmail.com         |"
    print *, "| Press / Media         | blackblazent.press@gmail.com            |"
    print *, ""
    print *, "### 🧪 Product & Feedback"
    print *, "| Product Feedback      | blackblazent.feedback@gmail.com         |"
    print *, "| Beta Testing          | blackblazent.beta@gmail.com             |"
    print *, "--------------------------------------------------------------------------------"
    print *, "🖤 Made with code and creativity by BlackBlazent"
end program BlackBlazentWelcome
